# HPA YAML example (if you used K8s manifests)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tasky-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tasky
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
