apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: NodePort
  selector:
    app: tasky
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31012  # You can also omit this line to let Kubernetes auto-select an available port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: tasky
          image: cvp01/tasky:3
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:mongo@10.1.1.4:27017/tasky?authSource=admin"
            - name: SECRET
              value: "secret123"
      imagePullSecrets:
        - name: regcred  # Only needed if cvp01/tasky:3 is private

