apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-pull
  namespace: backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "It works!"
          restartPolicy: OnFailure

