name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This will still trigger on any commit to the `main` branch
    paths:
      - '**/*.py'
      - '**/*.go'
      - '**/Dockerfile'
      - '**/*.md'  # This ensures the workflow runs on application code changes


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub (or your registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t cvp01/tasky:latest .
          docker push cvp01/tasky:latest

     # Step 5: Test the Docker Image (Spin up and check the file)
      - name: Run Container and Test File
        run: |
          # Spin up the container in detached mode
          docker run -d --name tasky-container cvp01/tasky:latest

          # Check if the file is inside the container
          docker exec tasky-container cat /app/wizexercise.txt
          docker exec tasky-container cat /app/dummy-key

          # Optionally, check the file's contents
          docker exec tasky-container cat /app/dummy-key | grep "dummy"

          # Clean up by stopping and removing the container
          docker rm -f tasky-container 
