name: Terraform Destroy

on:
  workflow_dispatch:  # Trigger manually from the GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize Terraform (sets up the backend)
      - name: Terraform Init
        run: |
          terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
                         -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER }}" \
                         -backend-config="key=terraform.tfstate" \
                         -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"

      # Run Terraform Destroy
      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="blob_conn_string=${{ secrets.BLOB_CONN_STRING }}"
        env:
          TF_LOG: DEBUG

