name: Terraform Deployment

on:
  push:
    paths:
      - 'main.tf'
      - 'variables.tf'
      - 'outputs.tf'

# check to see me

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Grant write permissions to the id-token (necessary for authentication)

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform (sets up the backend)
      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER }}" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"

      # Apply Terraform configurations (deploy infrastructure)
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="blob_conn_string=${{ secrets.BLOB_CONN_STRING }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_LOG: DEBUG

